---
#
# Ansible Playbook for building Instant Plexe
# Copyright (C) 2018 Christoph Sommer <sommer@ccs-labs.org>
#
# Documentation for this template is at http://veins.car2x.org/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


- name: Install base packages
  apt:
    state: present
    name:
      - bison
      - flex
      - tcl-dev
      - tk-dev
      - openjdk-11-jre
      - qt5-default
      - libopenscenegraph-3.4-dev
      - libosgearth-dev
      - openscenegraph-plugin-osgearth
      - xvfb
      - libwebkit2gtk-4.0-dev
      - doxygen
      - graphviz

- name: Create default directories
  become_user: plexe
  file:
    path: /home/plexe/{{item}}
    state: directory
    owner: plexe
    group: plexe
    mode: 0755
  with_items:
    - src

- name: Download source
  get_url:
    url: "{{ omnetpp_tarball_url }}"
    dest: "/home/plexe/src/{{ omnetpp_tarball_filename }}"
    checksum: "sha1:{{ omnetpp_tarball_sha1 }}"

- name: Unpack source
  become_user: plexe
  shell: |
    set -exu
    tar -xvf "{{ omnetpp_tarball_filename }}"
  args:
    executable: /bin/sh
    chdir: /home/plexe/src
    creates: "/home/plexe/src/{{ omnetpp_dir }}"

- name: Create symlink
  become_user: plexe
  file:
    src: "/home/plexe/src/{{ omnetpp_dir }}"
    dest: /home/plexe/src/omnetpp
    state: link

- name: Add to path
  become_user: plexe
  lineinfile:
    dest: /home/plexe/.shrc
    line: 'PATH="$PATH:$HOME/src/omnetpp/bin"'

- name: Build OMNeT++
  become_user: plexe
  shell: |
    set -exu
    source ~/.shrc
    xvfb-run ./configure
    make -j2
  args:
    executable: /bin/bash
    chdir: /home/plexe/src/omnetpp
    creates: /home/plexe/src/omnetpp/bin/opp_run


