---
omnetpp_tarball_url: https://github.com/omnetpp/omnetpp/releases/download/omnetpp-5.6.2/omnetpp-5.6.2-src-linux.tgz
omnetpp_tarball_filename: omnetpp-5.6.2-src-linux.tgz
omnetpp_tarball_sha1: 87254e1eaccbc403c51848581dd3a2b62882d6b9
omnetpp_dir: omnetpp-5.6.2
